List TESTPAPERONE = [
  {
    "questionId": 1,
    "level": 4,
    "level1Name": "失效可能性评分",
    "level2Name": "第三方破坏评分",
    "level3Name": "地面活动水平",
    "questionName": "地区等级",
    "questionScore": null,
    "questionType": 1,
    "isDone": 0,
    "checkedCode": null,
    "option": [
      {
        "optionName": "四级地区",
        "optionScore": 0,
        "optionCode": 1,
      },
      {
        "optionName": "三级地区",
        "optionScore": 2,
        "optionCode": 2,
      },
      {
        "optionName": "二级地区",
        "optionScore": 4,
        "optionCode": 3,
      },
      {
        "optionName": "一级地区",
        "optionScore": 6,
        "optionCode": 4,
      },
    ]
  },
  {
    "questionId": 2,
    "level": 4,
    "level1Name": "失效可能性评分",
    "level2Name": "第三方破坏评分",
    "level3Name": "地面活动水平",
    "questionName": "建设活动频繁程度",
    "questionScore": null,
    "questionType": 1,
    "isDone": 0,
    "checkedCode": null,
    "option": [
      {
        "optionName": "位于矿藏开发及重工业生产地区",
        "optionScore": 0,
        "optionCode": 1,
      },
      {
        "optionName": "位于在建的经济开发区",
        "optionScore": 1,
        "optionCode": 2,
      },
      {
        "optionName": "位于经常对周围地下设施维护地区",
        "optionScore": 1.5,
        "optionCode": 3,
      },
      {
        "optionName": "附近有清理水沟、修围墙等维护活动地区",
        "optionScore": 2,
        "optionCode": 4,
      },
      {
        "optionName": "无建设活动地区",
        "optionScore": 3,
        "optionCode": 5,
      },
    ]
  },
  {
    "questionId": 3,
    "level1Name": "失效可能性评分",
    "level2Name": "第三方破坏评分",
    "level3Name": "地面活动水平",
    "level": 4,
    "questionName": "对建设活动施工单位技术交底",
    "questionScore": null,
    "questionType": 1,
    "isDone": 0,
    "checkedCode": null,
    "option": [
      {
        "optionName": "未交底",
        "optionScore": 0,
        "optionCode": 1,
      },
      {
        "optionName": "图纸交底",
        "optionScore": 1,
        "optionCode": 2,
      },
      {
        "optionName": "现场交底",
        "optionScore": 3,
        "optionCode": 3,
      },
    ]
  },
  {
    "questionId": 4,
    "level": 4,
    "level1Name": "失效可能性评分",
    "level2Name": "第三方破坏评分",
    "level3Name": "地面活动水平",
    "questionName": "交通繁忙程度",
    "questionScore": null,
    "questionType": 1,
    "isDone": 0,
    "checkedCode": null,
    "option": [
      {
        "optionName": "附近有铁路、公路交通主干线",
        "optionScore": 0,
        "optionCode": 1,
      },
      {
        "optionName": "附近有公路交通线干线",
        "optionScore": 0.5,
        "optionCode": 2,
      },
      {
        "optionName": "附近有公路交通线、乡村公路、机耕道",
        "optionScore": 1,
        "optionCode": 3,
      },
      {
        "optionName": "几乎没有车辆通行",
        "optionScore": 2,
        "optionCode": 4,
      },
    ],
  },
  {
    "questionId": 5,
    "level": 4,
    "level1Name": "失效可能性评分",
    "level2Name": "第三方破坏评分",
    "level3Name": "地面活动水平",
    "questionName": "农业生产",
    "questionScore": null,
    "questionType": 1,
    "isDone": 0,
    "checkedCode": null,
    "option": [
      {
        "optionName": "上方进行大型机械化耕种，打苕沟，犁地等较深挖掘",
        "optionScore": 0,
        "optionCode": 1,
      },
      {
        "optionName": "少量挖掘深度小于50cm的浅土层农作物",
        "optionScore": 1,
        "optionCode": 2,
      },
      {
        "optionName": "无农业生产活动 ",
        "optionScore": 2,
        "optionCode": 3,
      },
    ],
  },
  {
    "questionId": 6,
    "level": 4,
    "level1Name": "失效可能性评分",
    "level2Name": "第三方破坏评分",
    "level3Name": "地面活动水平",
    "questionName": "地质勘查",
    "questionScore": null,
    "questionType": 1,
    "isDone": 0,
    "checkedCode": null,
    "option": [
      {
        "optionName": "附近有地质勘查",
        "optionScore": 0,
        "optionCode": 1,
      },
      {
        "optionName": "附近无地质勘查 ",
        "optionScore": 1,
        "optionCode": 2,
      },
    ],
  },
  {
    "questionId": 7,
    "level": 4,
    "level1Name": "失效可能性评分",
    "level2Name": "第三方破坏评分",
    "level3Name": "地面活动水平",
    "questionName": "野生动物",
    "questionScore": null,
    "questionType": 1,
    "isDone": 0,
    "checkedCode": null,
    "option": [
      {
        "optionName": "附近有老鼠打洞等野生动物活动",
        "optionScore": 0,
        "optionCode": 1,
      },
      {
        "optionName": "附近无老鼠打洞等野生动物活动 ",
        "optionScore": 1,
        "optionCode": 2,
      },
    ],
  },
  {
    "questionId": 8,
    "level": 4,
    "level1Name": "失效可能性评分",
    "level2Name": "第三方破坏评分",
    "level3Name": "非水下穿越管道埋深",
    "questionName": "埋深",
    "questionScore": null,
    "questionType": 2,
    "isDone": 0,
    "checkedCode": null,
    "option": [
      {
        "optionName": "跨越段或露管段",
        "optionScore": 0,
        "optionCode": 1,
      },
      {
        "optionName": "埋地段 ",
        "optionScore": null,
        "optionCode": 2,
      },
    ],
  },
];
